// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendingManagement.Data.EF;

#nullable disable

namespace SpendingManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221130053659_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            ConcurrencyStamp = "",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            RoleId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("SpendingManagement.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3dec58e8-9430-4f73-b2dd-d9c9e849c7bc",
                            DateOfBirth = new DateTime(2022, 11, 30, 12, 36, 58, 499, DateTimeKind.Local).AddTicks(4924),
                            Email = "leminhloi@gmail.com",
                            EmailConfirmed = true,
                            Gender = 2,
                            LockoutEnabled = false,
                            Name = "Lee Minh Loij",
                            NormalizedEmail = "LEMINHLOI@GMAIL.COM",
                            NormalizedUserName = "LEMINHLOI",
                            PasswordHash = "AQAAAAEAACcQAAAAECzuBw4SP+dUMp4v0hV0WDsggYPiy2zV7RSA0VjKyBNhq19D1r4GTslPYTYOTjfqrQ==",
                            PhoneNumber = "0948123432",
                            PhoneNumberConfirmed = true,
                            PhotoUrl = "",
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "leminhloi"
                        });
                });

            modelBuilder.Entity("SpendingManagement.Data.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LimitMoney")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(10000000000L);

                    b.Property<int>("UnitTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("SpendingManagement.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeOfCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            Description = "Tiền mua đồ ăn này nọ",
                            Name = "Tiền ăn",
                            TypeOfCategory = 1
                        },
                        new
                        {
                            Id = new Guid("f458a439-20c7-4a98-85e4-77459cb51dab"),
                            Description = "Tiền để thuê nhà này nọ",
                            Name = "Tiền nhà",
                            TypeOfCategory = 1
                        },
                        new
                        {
                            Id = new Guid("64a74972-0fcb-4c1f-9423-e7476cd7d73b"),
                            Description = "Tiền để đi đổ xăng",
                            Name = "Tiền xăng",
                            TypeOfCategory = 1
                        },
                        new
                        {
                            Id = new Guid("74fa08d6-5f84-4722-a274-87fa9a223c05"),
                            Description = "Tiền mua sắm cho sinh hoạt",
                            Name = "Tiền mua sắm",
                            TypeOfCategory = 1
                        },
                        new
                        {
                            Id = new Guid("eea2a6b9-a8e4-4d6f-a435-3c7cb5ce4638"),
                            Description = "Khác với những cái ở trên",
                            Name = "Khác",
                            TypeOfCategory = 1
                        },
                        new
                        {
                            Id = new Guid("920d7974-62a7-4490-8a4c-263947584c7c"),
                            Description = "Tiền lương",
                            Name = "Tiền lương",
                            TypeOfCategory = 0
                        },
                        new
                        {
                            Id = new Guid("13df1094-249b-442e-9877-34b7d6bb67f6"),
                            Description = "Tiền cho thuê",
                            Name = "Tiền cho thuê",
                            TypeOfCategory = 0
                        },
                        new
                        {
                            Id = new Guid("b68c1556-d198-44bb-8200-f9a0f8ec576a"),
                            Description = "",
                            Name = "Kinh doanh",
                            TypeOfCategory = 0
                        },
                        new
                        {
                            Id = new Guid("7a980fa3-1905-4d9f-9fb3-1b154d6dab0e"),
                            Description = "",
                            Name = "Quà tặng",
                            TypeOfCategory = 0
                        },
                        new
                        {
                            Id = new Guid("e0981d40-787e-4fa6-9a10-8a59cb2b7b9b"),
                            Description = "Khác với những cái ở trên",
                            Name = "Khác",
                            TypeOfCategory = 0
                        });
                });

            modelBuilder.Entity("SpendingManagement.Data.Entities.Expenditure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenditures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d55a36a4-a592-49d4-abb4-97be4f6932fe"),
                            AppUserId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            CategoryId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            Cost = 100000L,
                            DateCreate = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = ""
                        },
                        new
                        {
                            Id = new Guid("2d397fa1-5739-4639-a3e6-ff45d5993216"),
                            AppUserId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            CategoryId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            Cost = 20000L,
                            DateCreate = new DateTime(2022, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = ""
                        },
                        new
                        {
                            Id = new Guid("2784bc9c-2dc9-40de-bc87-af5797a2cb08"),
                            AppUserId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            CategoryId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            Cost = 10000L,
                            DateCreate = new DateTime(2022, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = ""
                        });
                });

            modelBuilder.Entity("SpendingManagement.Data.Entities.Budget", b =>
                {
                    b.HasOne("SpendingManagement.Data.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SpendingManagement.Data.Entities.Expenditure", b =>
                {
                    b.HasOne("SpendingManagement.Data.Entities.AppUser", "AppUser")
                        .WithMany("Expenditures")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpendingManagement.Data.Entities.Category", "Category")
                        .WithMany("Expenditures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SpendingManagement.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Expenditures");
                });

            modelBuilder.Entity("SpendingManagement.Data.Entities.Category", b =>
                {
                    b.Navigation("Expenditures");
                });
#pragma warning restore 612, 618
        }
    }
}
